### PR TITLE
Add Swift generator script for the source file

### PR DESCRIPTION
**Pull request by mokagio**
It's written in Swift and slightly functional, which seems appropriate ☺️

It might be a bit silly to add this at this point, since the framework is there already, but hey it might come in handy later on ¯_(ツ)_/¯

### CODE REVIEW

**Comment by tonyd256** [comment]
SO META

**Comment by gfontenot** [comment]
This is certifiably insane. I dig it.

I do wonder about its usefulness. I have to believe that supporting out to 26 arguments is already beyond a reasonable amount to support. Especially given that we're working against the compiler once we pass 16 arguments.

I do wish I had been smart enough to write this instead of hand writing all of the implementations by hand though.

**Comment by mokagio** [comment]
> I do wonder about its usefulness.

It isn't. I made it up mainly for fun.

>  I have to believe that supporting out to 26 arguments is already beyond a reasonable amount to support.

Why don't you have `User` models that get 20 parameters in its constructor? That's in line with [Sandi Metz's rules](https://robots.thoughtbot.com/sandi-metz-rules-for-developers) right? :stuck_out_tongue_closed_eyes: 

>  I do wish I had been smart enough to write this instead of hand writing all of the implementations by hand though.

I'm pretty sure it took me more time to make that work than it took you to write that

**Comment by mokagio** [comment]
That all said... Maybe if I made that `let threshold = 16` actually a parameter read from the script invocation, this could be consider _slightly_ more useful.

**Comment by gfontenot** [comment]
@mokagio Again, this is dope. Thanks for the work here. I'm going to close this since it's subsumed by #10

**Comment by mokagio** [comment]
No worries. Cheers 🍻

Giovanni Lodi - Freelance iOS Developer - +61 (0)467 041 198

homepage: giovannilodi.com

blog: mokacoding.com

github: mokagio

twitter: @mokagio

**Pull request closed without merging**
