### PR TITLE
Add tvOS target

### PR DESCRIPTION
**Pull request by nickygerritsen**
I'm not sure whether you already want to add this before the watchOS SDK gets a GM or stable release, but nevertheless you can then probably use it later without changing much. I needed it anyway to test an SDK I am creating on tvOS so I might as well create a PR for it :).

### CODE REVIEW

**Comment by gfontenot** [comment]
This is fantastic, thanks for putting this together.

In order to keep Carthage installs from breaking, we can't ship a shared scheme. Do you mind _un_sharing the scheme for now, and I will make a branch that you can point at that will have a shared scheme?

**Comment by nickygerritsen** [comment]
No problem, will do this tomorrow :)

**Comment by nickygerritsen** [comment]
OK it is unshared now. The scheme is now not committed, because it is in my xcuserdata directory. Is that correct or should I commit the file anyway?

**Comment by gfontenot** [comment]
Nope, that's exactly right. I'll check that box in a `tvos` branch and that'll commit it into the repo.

**Comment by nickygerritsen** [comment]
But you can't access that box now right? Because the scheme is not there... Or do I miss something here

**Comment by gfontenot** [comment]
It is. Xcode auto-creates the scheme for the current user when you open the project.

**Comment by nickygerritsen** [comment]
Ahhhh ok. Magic!

**Comment by nickygerritsen** [comment]
@gfontenot Are you waiting on me for something to merge this one or am I missing something?

**Comment by gfontenot** [comment]
Nope, sorry, just haven't had time. Will get to this ASAP.

**Comment by gfontenot** [comment]
bam

asap'd

Thanks!

**Comment by gfontenot** [comment]
And I've created a `tvos` branch if anyone wants to point at that directly.

**Comment by bruceflowers** [comment]
@nickygerritsen want to put up a PR for the tvOS branch resharing the scheme? If you're busy, just let me know, and I can do it

**Pull request merged**
