### PR TITLE
Use universal build settings

### PR DESCRIPTION
**Pull request by gfontenot**
Curry is a really simple framework, and it sucks to have to manage multiple
targets and schemes to properly distribute it. Instead, we can use some [clever
xcconfigs](https://github.com/mrackwitz/xcconfigs) to let a single framework target (and a single scheme) build
multiple frameworks for us.

### CODE REVIEW

**Comment by gfontenot** [comment]
I want to test this against some demo apps to make _absolutely_ sure this works as advertised.

**Comment by gfontenot** [comment]
Confirmed that this works against https://github.com/gfontenot/platformtests

:tada:

**Comment by paulyoung** [comment]
I've been thinking about this since I saw it in [kylef/Mockingjay](https://github.com/kylef/Mockingjay). Would be great if it's a viable solution!

**Comment by gfontenot** [comment]
Ditto. Ever since you pointed this out as a potential option, I haven't been able to stop thinking about it.

**Comment by paulyoung** [comment]
The only potential downside I can see to this is described here: https://github.com/the-grid/Disc/pull/9

**Comment by paulyoung** [comment]
Specifically:

> Because Mockingjay is a universal framework, Xcode can't infer the correct device for the scheme so sometimes combinations like Disc-iOS > My Mac can be set. This means sometimes having to manually pick the correct device for the scheme before building or running tests.

**Comment by paulyoung** [comment]
But that's only a problem because we disabled implicit dependencies.

**Comment by gfontenot** [comment]
That's interesting though, and honestly might be enough of a PITA to avoid this (unfortunately).

**Comment by gfontenot** [comment]
I wish Apple would support this kind of thing natively.

**Comment by paulyoung** [comment]
There may be a way around it but I tried a few things and haven't been able to find one.

I want to reiterate that using the default build scheme settings, "Find Implicit Dependencies" is enabled and doesn't appear to be subject to that behavior.

**Comment by gfontenot** [comment]
I'm going to go ahead and close this. I think it'd be nice, but it seems like it's more headache than it's worth.

**Pull request closed without merging**
