### PR TITLE
Record Swift migration to suppress conversion dialogs on Xcode 8

### PR DESCRIPTION
**Pull request by ikesyo**
It would be great if this is merged into `master` and also into `v2.3.2`, then v2.3.3 is released with this fix. 🙏

### CODE REVIEW

**Comment by gfontenot** [comment]
It looks like we don't actually have an official Swift 3.0 release out yet, so I think we just need to release v2.3.3 from master?

This is annoying to have to keep track of.

**Comment by gfontenot** [comment]
Oh, oops, yes we do. I didn't have the full history locally.

**Comment by gfontenot** [comment]
Done! Merged in as 0d1db3e into `master` and a8e261e for the release of 2.3.3.

Thanks!

**Comment by ikesyo** [comment]
Many thanks for the quick work! ⚡

**Pull request closed without merging**
