### PR TITLE
Add type annotations on closure arguments for reducing times of type inference

### PR DESCRIPTION
**Pull request by ikesyo**
This speeds up the build time about 2x faster on my local machine. :zap: Could you take a look?

### CODE REVIEW

**Comment by tonyd256** [comment]
Oh, very interesting! We'll definitely try this on our end. Would you be able to remove the backticks on the capital letters (the Types)? And if so does that effect the build time?

**Comment by gfontenot** [comment]
@ikesyo Great call. This is fantastic. +1 to removing the backticks around the types, and I'd also be curious to know if this helps us add some more definitions of `curry`. I'm happy to look into that myself if you don't want to play around with it.

**Comment by ikesyo** [comment]
I removed the backticks from the types. :sparkles: 

I tried with more definitions and the result is the following on my machine:
- 20 withouth this change: about 20 seconds
- 20: about 12 seconds
- 21: about 20 seconds
- 22: about 38 seconds

So still 20 seems reasonable number to me, increasing to 21 would not be so useful. How do you feel?

**Comment by mbrandonw** [comment]
Turns out if you go _allllll_ the way with specifying types you can make this stuff compile way faster. For example, here is a curry for 21 arguments:

``` swift
func curry<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V>(function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U) -> V) -> A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T -> U -> V {
  return { (a: A) -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T -> U -> V in
    { (b: B) -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T -> U -> V in
      { (c: C) -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T -> U -> V in
        { (d: D) -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T -> U -> V in
          { (e: E) -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T -> U -> V in
            { (f: F) -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T -> U -> V in
              { (g: G) -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T -> U -> V in
                { (h: H) -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T -> U -> V in
                  { (i: I) -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T -> U -> V in
                    { (j: J) -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T -> U -> V in
                      { (k: K) -> L -> M -> N -> O -> P -> Q -> R -> S -> T -> U -> V in
                        { (l: L) -> M -> N -> O -> P -> Q -> R -> S -> T -> U -> V in
                          { (m: M) -> N -> O -> P -> Q -> R -> S -> T -> U -> V in
                            { (n: N) -> O -> P -> Q -> R -> S -> T -> U -> V in
                              { (o: O) -> P -> Q -> R -> S -> T -> U -> V in
                                { (p: P) -> Q -> R -> S -> T -> U -> V in
                                  { (q: Q) -> R -> S -> T -> U -> V in
                                    { (r: R) -> S -> T -> U -> V in
                                      { (s: S) -> T -> U -> V in
                                        { (t: T) -> U -> V in
                                          { (u: U) -> V in
                                            function(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u)
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

That compiles in about 0.2 seconds! If I drop the return types for each inner closure it jumps to 15 seconds! I'd be willing to help out with this change if needed.

Nice side effect, it produces some funky looking source code...

**Comment by gfontenot** [comment]
Haha, amazing.

I'm _totally_ fine with `Curry.framework` containing completely bonkers unreadable code as long as:
1. It improves performance
2. It's generated and I never have to _actually_ write it

I think adding all of that insane type info into the generator should be fairly straightforward. @ikesyo do you want to handle this as part of this PR? Or would you rather merge in your changes as-is and I can tackle this change after?

**Comment by mbrandonw** [comment]
Yeah this seems worth it. Just took some benchmarks. Times still get bad for high number of params, but are much better for lower number of params:
- 18 arguments (current # in Curry.framework): 2s
- 19 arguments: 3s
- 20 arguments: 5s
- 21 arguments: 9s
- 22 arguments: 17s

So, we could increase number of arguments to 22 while keeping about the same compile time, or keep the same number of arguments and reduce compile time to just 2 seconds.

I'll be honest, I went down this road today cause I upgraded to Curry 2.0 and realized I am now missing a curry that I used to use :/ I know I know, seems bonkers, but alas that's the reality. Worse case I'll just define the extra curries myself.

**Comment by gfontenot** [comment]
Yeah, I wish we hadn't had to remove instances of `curry` for 2.0, hadn't thought about adding more type info unfortunately.

It's crazy to me that we _still_ can't get past 21 or 22 arguments without crippling compile times. I feel like I'd be willing to bump to 21 for now with the added type info and hopefully we'll be able to keep pushing the number up with compiler updates.

Out of curiosity, @mbrandonw, how many arguments are you trying to curry out to? My gut says if we can get back to ~26 arguments (+1 return value) we should be able to cover basically all realistic functions, but maybe I'm wrong about that.

**Comment by mbrandonw** [comment]
It does seem that sum of compile times _per_ curry function is dramatically less than the cumulative compile time for all the functions at once. I'm seeing .2 seconds for the 21 argument curry, yet compiling all <=21 argument curries together takes 9 seconds. I would hope for less than 21 \* .2 = 4 seconds.

> Out of curiosity, @mbrandonw, how many arguments are you trying to curry out to?

I'm sitting at 21 right now :/

I really wish I wasn't. But the API I'm interacting with returns the data in this manner instead of nesting it in a more sane structure (well, I wrote the API long time ago, so only have myself to blame).

As far as I can tell, if my API is sending 21 fields I'm pretty much out of luck. Is this correct? My Swift model has a more sane nested structure, but I don't see anyway around the fact that the API is not nested.

**Comment by gfontenot** [comment]
> It does seem that sum of compile times per curry function is dramatically less than the cumulative compile time for all the functions at once.

I'd assume because overloading `curry` (especially this many times) creates increased work for the compiler? Whereas if you just define a single `curry` with exactly the number of arguments you need, it has to do much less work. We _could_ go Full Blown Haskell on this and create `curry`, `curry2`, `curry21` etc, but that seems like it'd suck even more.

> As far as I can tell, if my API is sending 21 fields I'm pretty much out of luck. Is this correct? My Swift model has a more sane nested structure, but I don't see anyway around the fact that the API is not nested.

I'd probably have to get more info on the actual code to say for sure. I feel like `curry` should relate more to the number of arguments your model takes than the number of fields in your JSON, though. Want to create a new issue here (or under Argo) to discuss this further? I'd love to help if possible.

**Comment by mbrandonw** [comment]
Yeah you're right, unique names speed this up so much. 22 arguments in 3.5 seconds. Still not sure why that would matter so much, but I'm also not well versed in the swift compiler. I don't think the numbered curry functions is terrible, but I fear the error messages will be too confusing when using the incorrect `curryN`.

>  Want to create a new issue here (or under Argo) to discuss this further? I'd love to help if possible.

Yeah, I'll open an issue later today. Thanks!

**Comment by mbrandonw** [comment]
> Want to create a new issue here (or under Argo) to discuss this further? I'd love to help if possible.

you know, while writing this up i totally figured it out. i was just being silly and it became painfully obvious once I just looked to the types :/

this might be useful to have in the documentation. if you point me to an appropriate place to add such things i'd be willing to write up some notes on properly nesting models to avoid the `curry` limitations.

**Comment by mbrandonw** [comment]
By documentation I mean for Argo of course...

**Comment by gfontenot** [comment]
We have a [Documentation directory](https://github.com/thoughtbot/Argo/tree/master/Documentation) in Argo that would be perfect for this kind of thing (and we _desperately_ need these kinds of contributions).

**Comment by gfontenot** [comment]
@ikesyo Awesome! Thanks so much. I've reworded the commits for consistency and merged them into master as a9f760e, 63ea71d, 93db511, and 70f1a2b

I'll ship this as a 2.1 release now.

**Comment by mbrandonw** [comment]
👏 thanks everyone! 👏

**Comment by ikesyo** [comment]
Thank you!

**Pull request closed without merging**
