### PR TITLE
Add support for Swift Package Manager

### PR DESCRIPTION
**Pull request by gfontenot**
I need to test to make sure this works, but `swift build` doesn't seem to
complain.

### CODE REVIEW

**Comment by jakecraige** [comment]
Is the sources change a new thing?

**Comment by gfontenot** [comment]
@jakecraige That's the convention laid out by swift package manager. Files inside `Sources/` are automatically added to the package.

**Comment by tonyd256** [comment]
:+1:

**Comment by gfontenot** [comment]
Ok, _now_ this builds properly. The `Sources/Resources` dir (or that directory's contents) caused issues with `swift build`.

**Comment by NachoSoto** [comment]
:heart_eyes:

**Comment by Ashton-W** [comment]
Sources is the default, you could of supplied a source directory, right?

**Comment by paulyoung** [comment]
@Ashton-W I couldn't see anything about how to specify one yet. Did you read that somewhere?

**Comment by gfontenot** [comment]
@paulyoung @Ashton-W Yeah, turns out that's what the `targets` key is. This _could_ have been done as:

``` swift
let package = Package(
  name: "Curry",
  targets: [
    Target(name: "Source")
  ]
)
```

**Comment by Ashton-W** [comment]
`Source` should have worked anyway 🐒

> Sub directories of a directory named Sources, Source, srcs or src become modules

https://github.com/apple/swift-package-manager/blob/master/Documentation/SourceLayouts.md

**Comment by gfontenot** [comment]
It's also possible that the `Resources` thing was screwing it up. Let me check.

**Comment by gfontenot** [comment]
Confirmed. `Source` is Totally A OK and works by default.

**Comment by jpsim** [comment]
Is anything holding this back? I'd love to see this merged :smile:

**Comment by gfontenot** [comment]
@jpsim nothing other than pure unabashed laziness. I'll get this into master today.

**Pull request merged**
