### PR TITLE
Add implementations for curry out to 15 arguments

### PR DESCRIPTION
**Pull request by gfontenot**
This adds `curry` out to 15 arguments. There are implementations for up
to 26 arguments, but compile times become exponential past 15 arguments
(15 arguments takes 2 seconds on my machine, 18 arguments takes 10
seconds.)

### CODE REVIEW

**Comment by tonyd256** [comment]
:+1:

**Comment by croaky** [comment]
For the README:

steph

**Comment by gfontenot** [comment]
whats this sf stuff doing in here

**Comment by croaky** [comment]
[Lights](http://youtu.be/dIRkowObTQM)

**Pull request merged**
