### PR TITLE
Add .swift-version file for proper spec treatment by CocoaPods.

### PR DESCRIPTION
**Pull request by jshier**
This PR adds the `.swift-version` file so that `Curry.podspec` properly lints using CocoaPods 1.1 and can then be pushed to trunk (which 3.0.0 needs to be).

### CODE REVIEW

**Comment by tonyd256** [comment]
@jshier Sorry, I ended up doing this before I saw this.

**Comment by tonyd256** [comment]
However, I think cocoapods rewrote my git config when I called trunk push ... which is not cool.

**Comment by jshier** [comment]
No problem, I'm just interested in getting this pushed to trunk. 👍

**Comment by tonyd256** [comment]
it should be now ... trying to figure out what went wrong though before I release our other libs.

**Pull request closed without merging**
